### ISSUE TITLE
not work 4.0.6

### ISSUE THREAD

**Issue by ashrafalzyoud** [TaoufikMejri/redmine_alert_issue#1]
uninitialized constant AlertWorker::Sidekiq (NameError)
  /home/redmine/4.0.6/plugins/redmine_alert_issue/app/workers/alert_worker.rb:2:in `<class:AlertWorker>'
  /home/redmine/4.0.6/plugins/redmine_alert_issue/app/workers/alert_worker.rb:1:in `<top (required)>'
  /home/redmine/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
  /home/redmine/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
  /home/redmine/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/acti

**Comment by TaoufikMejri** [comment]
Add redmine_sidekiq plugin to your plugins

**Comment by ashrafalzyoud** [comment]
can u explain what this plugin do

**Comment by TaoufikMejri** [comment]
When the user create a new issue, he must change status within two hours,
if not an alert occurs.

Le jeu. 12 mars 2020 à 11:29 PM, ashrafalzyoud <notifications@github.com> a
écrit :

**Comment by ashrafalzyoud** [comment]
@TaoufikMejri 
its working in redmine 5.1?
